/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationCard: typeof import('./src/components/ApplicationCard.vue')['default']
    BannerComponent: typeof import('./src/components/BannerComponent.vue')['default']
    CategoryComponent: typeof import('./src/components/CategoryComponent.vue')['default']
    CompanyCard: typeof import('./src/components/CompanyCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FilterComponent: typeof import('./src/components/FilterComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HeaderUserInfoComponent: typeof import('./src/components/HeaderUserInfoComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    JobCard: typeof import('./src/components/JobCard.vue')['default']
    JobIndexCard: typeof import('./src/components/JobIndexCard.vue')['default']
    LoadFailedComponent: typeof import('./src/components/LoadFailedComponent.vue')['default']
    LoadingComponent: typeof import('./src/components/LoadingComponent.vue')['default']
    RecommendList: typeof import('./src/components/RecommendList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./src/components/SearchComponent.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
