# Generated by Django 4.2.1 on 2025-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
